[package]
name = "qrzero-radio"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["io-util"] }
tracing.workspace = true
quick-xml = "0.38"
futures-util = "0.3"
tokio-tungstenite = "0.27"
serialport = { version = "4", default-features = false }

[dev-dependencies]
tokio = { workspace = true, features = ["io-util", "test-util"] }
